public with sharing class ReusableMultiSelectLookupController {
    @AuraEnabled
    public static List<ResultWrapper> fetchRecords(SearchWrapper inputWrapper) {
        try {
            if(inputWrapper != null){
                string filterCriteria='';
                List<String> searchKeywordList = inputWrapper.searchString.split(' ');
                for(String kw : searchKeywordList){
                    filterCriteria += inputWrapper.fieldApiName + ' LIKE \'%'+kw+'%\' OR ';
                }
                if(string.isNotBlank(inputWrapper.otherFieldApiName) && inputWrapper.searchByOtherField){
                    for(String kw : searchKeywordList){
                    filterCriteria+= inputWrapper.otherFieldApiName + ' LIKE \'%'+kw+'%\' OR ';
                    }
                }
                filterCriteria = filterCriteria.removeEnd(' OR ');
                String fieldsToQuery = 'SELECT Id, ';
                if(string.isNotBlank(inputWrapper.fieldApiName)){
                    fieldsToQuery = fieldsToQuery + inputWrapper.fieldApiName;
                }
                if(string.isNotBlank(inputWrapper.otherFieldApiName)){
                    fieldsToQuery = fieldsToQuery + ', ' + inputWrapper.otherFieldApiName;
                }
                String query = fieldsToQuery + ' FROM '+ inputWrapper.objectApiName;
                if(String.isNotBlank(inputWrapper.parentFieldApiName) && String.isNotBlank(inputWrapper.parentRecordId)){
                    query += ' WHERE '+ inputWrapper.parentFieldApiName+ ' = \''+ inputWrapper.parentRecordId + '\'';
                    query += ' AND (' + filterCriteria+' ) Order By '+ inputWrapper.fieldApiName+' Limit 10';
                } 
                else {
                    query += ' WHERE '+ filterCriteria+' Order By '+ inputWrapper.fieldApiName+' Limit 10';
                }
                List<ResultWrapper> returnWrapperList = new List<ResultWrapper>();
                for(SObject s : Database.query(query)) {
                    ResultWrapper wrap = new ResultWrapper();
                    wrap.mainField = (String)s.get(inputWrapper.fieldApiName);
                    wrap.subField = (String)s.get(inputWrapper.otherFieldApiName);
                    wrap.id = (String)s.get('id');
                    returnWrapperList.add(wrap);
                }
                return returnWrapperList;
            }
            return null;
        } catch (Exception err) {
            throw new AuraHandledException(err.getMessage());
        }
    }

    public class ResultWrapper{
        @AuraEnabled public String mainField{get;set;}
        @AuraEnabled public String subField{get;set;}
        @AuraEnabled public String id{get;set;}
    }

    public class SearchWrapper {
        @AuraEnabled public String objectApiName{get;set;}
        @AuraEnabled public String fieldApiName{get;set;}
        @AuraEnabled public String otherFieldApiName{get;set;}
        @AuraEnabled public String searchString{get;set;}
        @AuraEnabled public String parentRecordId{get;set;}
        @AuraEnabled public String parentFieldApiName{get;set;}
        @AuraEnabled public Boolean searchByOtherField{get;set;}
    }
}